### ISSUE TITLE
Configuration reference misspelling

### ISSUE THREAD

**Issue by rpousa** [srsran/srsRAN_Project_docs#7]
amf:
  bind_adddr:  (bind_addr)
cell_cfg:
  pucch:
    p0_nomial: (p0_nominal)
    f1_nof_cells_res_sr: (f1_nof_cell_res_sr)
    f2_nof_cells_res_csi: (f2_nof_cell_res_csi)

(Hello, I'm quite new to this but I found this project while working on my thesis. In importing the full config reference and commenting out the unnecessary options I found a few misspellings. Albeit pedantic, changing them might help future adopters)

Currently, I have it running, and the "corrections" in parenthesis come from the gnb_appconfig files so I assume they are correctly being taken as configurations while running. 

Looking forward to seeing what is being cooked up for the future

**Comment by brendan-mcauliffe** [comment]
Hi @rpousa, good catch. Thanks for reporting! I've updated the public docs with these changes.
