### ISSUE TITLE
phy-low with split-7.2 and split-8

### ISSUE THREAD

**Issue by Zplusless** [srsran/srsRAN_Project_docs#8]
Hi, I'm learning split-7.2 and split-8 and found this parts in the doc confusing.

In `srsRAN_Project_docs/docs/source/knowledge_base/source/gnb_components/source/index.rst`, the low phy locates in the DU for split-8 in the Figure. But the doc explain it as "If split 7.2x is being used then the low-PHY will be located in the DU-low (supposed to be RU?), if split 8 is being used it will be located in the RU(supposed to be DU?)." According to `srsRAN_Project_docs/docs/source/knowledge_base/source/oran_gnb/source/index.rst`. Under Fig.15, "Split 7.2 moves to low PHY out to the RU , while Split 8 keeps it within the DU-low." 

I'm new to this. So please correct me if I'm wrong.

**Comment by brendan-mcauliffe** [comment]
Hi @Zplusless you are right, this is a typo. I will update the document now. Split 8 means the low PHY will be in the DU-low, while in split 7.2x it will be located in the RU.

**Comment by Zplusless** [comment]
> Hi @Zplusless you are right, this is a typo. I will update the document now. Split 8 means the low PHY will be in the DU-low, while in split 7.2x it will be located in the RU.

Thanks！
